#!/bin/bash
# since Bash v4 

echo ${str}


output="pavin_0.v05_0v9_0v06_1500_0v015_0v5"
echo $output
echo $r

for ((i=0; i<40; i++));
do
let j=i+1
#     /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/hist_registration /home/julia/Documents/data_base/hokuyo/pcd/Hokuyo_$j.pcd /home/julia/Documents/data_base/hokuyo/pcd/Hokuyo_$i.pcd 0.035 0.3 0 0.004 0.02 10000 0.02 0.2
#     /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/hist_registration /home/julia/Documents/data_base/hokuyo/pcd/Hokuyo_$j.pcd /home/julia/Documents/data_base/hokuyo/pcd/Hokuyo_$i.pcd 0.3 0.3 0 0.006 0.03 8000 0.02 0.2 30cm
#     /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/hist_registration /home/julia/Documents/data_base/Pavin1_ascii/pcd/scan"$j"00.pcd /home/julia/Documents/data_base/Pavin1_ascii/pcd/scan$"$i"00.pcd 0.02 0.6 0 0.003 0.02 1000 0.015 0.2 pavin_5cm_1000 
/home/julia/Desktop/my_programs/hist_registration/build-hist_registration/hist_registration /home/julia/Documents/data_base/Pavin1_ascii/pcd/scan"$j"00.pcd /home/julia/Documents/data_base/Pavin1_ascii/pcd/scan$"$i"00.pcd 0.05 0.9 0 0.06 1500 0.015 0.5 $output

#   	/home/julia/Desktop/my_programs/hist_registration/build-hist_registration/hist_registration /home/julia/Documents/data_base/hokuyo/pcd/Hokuyo_$j.pcd /home/julia/Documents/data_base/hokuyo/pcd/Hokuyo_$i.pcd 0.06 0.1 0 0.1 1000 0.015 0.2 hokuyo 
done   

/home/julia/Desktop/my_programs/multiply_transformations/build-multiply_transform/multiply_transform /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output

/home/julia/Desktop/my_programs/closed_loop/build-closed_loop/closed_loop /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output


for ((i=0; i<40; i++));
do
let j=i+1
str="$str-O /home/julia/Documents/data_base/Pavin1_ascii/txt/scan"$j"00.txt -APPLY_TRANS /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output/scan"$j"00_scan000.txt -CLEAR "
done
echo $str
cd /home/julia/
./CloudCompare $str

