#!/bin/bash
# since Bash v4 

output="pavin"

echo $output

for ((i=0; i<40; i++));
do
let j=i+1
/home/julia/Desktop/my_programs/hist_registration/build-hist_registration/hist_registration /home/julia/Documents/data_base/pavin/pcd/scan"$j"00.pcd /home/julia/Documents/data_base/pavin/pcd/scan"$i"00.pcd 0.1 0.6 0 0.02 600 0.05 0.2 $output 35
done   

mkdir /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output/to_000

/home/julia/Desktop/my_programs/multiply_transformations/build-multiply_transform/multiply_transform /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output/to_000

/home/julia/Desktop/my_programs/closed_loop/build-closed_loop/closed_loop /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output/to_000


for ((i=0; i<40; i++));
do
let j=i+1
str="$str-O /home/julia/Documents/data_base/pavin/txt/scan"$j"00.txt -APPLY_TRANS /home/julia/Desktop/my_programs/hist_registration/build-hist_registration/results/transformations/$output/to_000/scan"$j"00_scan000.txt -CLEAR "
done

cd /home/julia/
./CloudCompare $str

mkdir /home/julia/Documents/data_base/pavin/txt/transformed/
rm /home/julia/Documents/data_base/pavin/txt/transformed/*.bin
mv /home/julia/Documents/data_base/pavin/txt/*bin /home/julia/Documents/data_base/pavin/txt/transformed/
mv /home/julia/Desktop/raccourci_hist_results/$output/to_000/scan2900_scan900.txt /home/julia/Documents/data_base/pavin/transforms/my_method/closed_loop/

/home/julia/Desktop/my_programs/validation/build-validation/validation my_method/ 2900 900
